name: jennifer_sqlite3_adapter
version: 0.4.0
crystal: ">= 0.36.0"

authors:
  - Roman Kalnytskyi <moranibaca@gmail.com>

development_dependencies:
  sqlite3:
    github: crystal-lang/crystal-sqlite3
    version: "0.19.0"
  jennifer:
    github: imdrasil/jennifer.cr
    branch: master
  sam:
    github: imdrasil/sam.cr

license: MIT
