name: CI

on:
  pull_request:
    branches: "*"
  push:
    branches: master
  schedule:
    - cron: "0 7 * * 1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - crystal_version: 1.0.0
          - crystal_version: 1.1.0
          - crystal_version: 1.2.2
          - crystal_version: 1.3.2
          - crystal_version: 1.4.1
          - crystal_version: 1.5.1
          - crystal_version: 1.6.1
          - crystal_version: 1.6.1
            sqlite_version: 3360000
            sqlite_year: 2021
          - crystal_version: 1.6.1
            sqlite_version: 3370200
            sqlite_year: 2022
          - crystal_version: 1.6.1
            sqlite_version: 3380300
            sqlite_year: 2022
            lint: true

    runs-on: ubuntu-latest

    env:
      SQLITE_VERSION: ${{ matrix.sqlite_version }}
      SQLITE_YEAR: ${{ matrix.sqlite_year }}

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1

      - name: Donwload sources
        uses: actions/checkout@v2

      - name: Check formatting
        if: ${{ matrix.lint }}
        run: crystal tool format --check

      - name: Install dependencies
        run: |
          function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
          if [ $(version '${{ matrix.crystal_version }}') -lt $(version '1.6.1') ]; then
            cp .github/shard_1_5_1.yml shard.yml
          fi
          shards install

      - name: Run linter
        if: ${{ matrix.lint }}
        run: ./bin/ameba

      - name: Install SQLite3
        run: bash .github/install_sqlite.sh

      - name: Run migrations
        run: crystal sam.cr db:setup

      - name: Run specs
        run: crystal spec
